name: HuskHomes
version: '${project.version}'
main: me.william278.huskhomes2.HuskHomes
api-version: 1.16
authors: [William278]
softdepend: [dynmap, Vault, BlueMap, Squaremap]
description: A powerful, intuitive and flexible teleportation suite
website: 'https://william278.net'
libraries:
  - redis.clients:jedis:4.0.1

commands:
  home:
    usage: /<command> <home>
    permission: huskhomes.home
  sethome:
    usage: /<command> <name>
    permission: huskhomes.sethome
  delhome:
    usage: /<command> <name/all>
    permission: huskhomes.delhome
  edithome:
    usage: /<command> <home> <rename/description/location/public/private> [arguments]
    permission: huskhomes.edithome
  warp:
    usage: /<command> <warp>
    permission: huskhomes.warp
  setwarp:
    usage: /<command> <name>
    permission: huskhomes.setwarp
  delwarp:
    usage: /<command> <name/all>
    permission: huskhomes.delwarp
  editwarp:
    usage: /<command> <warp> <rename/description/location> [arguments]
    permission: huskhomes.editwarp
  back:
    usage: /<command>
    permission: huskhomes.back
  homelist:
    usage: /<command> <page>
    permission: huskhomes.home
    aliases: [homes, listhomes]
  warplist:
    usage: /<command> <page>
    permission: huskhomes.warp
    aliases: [warps, listwarps]
  publichomelist:
    usage: /<command> <page>
    permission: huskhomes.publichome
    aliases: [phomes, phomelist, listphomes, listpublichomes]
  publichome:
    usage: /<command> <owner.home>
    permission: huskhomes.publichome
    aliases: [phome]
  tp:
    usage: /<command> <player/coordinates>
    permission: huskhomes.tp
    aliases: [tpo]
  tphere:
    usage: /<command> <player>
    permission: huskhomes.tphere
    aliases: [tpohere]
  tpa:
    usage: /<command> <player>
    permission: huskhomes.tpa
    aliases: [tprequest, tpask]
  tpahere:
    usage: /<command> <player>
    permission: huskhomes.tpahere
    aliases: [tphererequest, tpaskhere]
  tpaccept:
    usage: /<command> [player]
    permission: huskhomes.tpaccept
    aliases: [tpyes]
  tpdeny:
    usage: /<command> [player]
    permission: huskhomes.tpdeny
    aliases: [tpno]
  tpignore:
    usage: /<command>
    permission: huskhomes.tpignore
    aliases: [tpaignore, ignoretprequests]
  tpoffline:
    usage: /<command> <player>
    permission: huskhomes.tpoffline
  rtp:
    usage: /<command>
    permission: huskhomes.rtp
    aliases: [randomtp, randomteleport, wild]
  spawn:
    usage: /<command>
    permission: huskhomes.spawn
  setspawn:
    usage: /<command>
    permission: huskhomes.spawn.set
  tpaall:
    usage: /<command>
    aliases: [tpaallhere, tpahereall, tprequestall]
    permission: huskhomes.tpaall
  tpall:
    usage: /<command>
    aliases: [tphereall, tpallhere]
    permission: huskhomes.tpall
  huskhomes:
    usage: /<command> <about/update/reload/migrate>

permissions:
  huskhomes.*:
    description: Grants all HuskHomes permissions
    children:
      huskhomes.bypass_timers: true
      huskhomes.commands: true
      huskhomes.private_home_admin: true
  huskhomes.private_home_admin:
    description: Lets you access and edit private homes
    children:
      huskhomes.home.other: true
      huskhomes.edithome.other: true
      huskhomes.delhome.other: true
  huskhomes.bypass_timers:
    description: Bypass all timer restrictions.
    children:
      huskhomes.bypass_timer: true
      huskhomes.rtp.bypass_cooldown: true
  huskhomes.basic:
    description: Access a basic pack of commands, good for Survival servers
    children:
      huskhomes.home: true
      huskhomes.sethome: true
      huskhomes.delhome: true
      huskhomes.edithome: true
      huskhomes.edithome.public: true
      huskhomes.publichome: true
      huskhomes.back: true
      huskhomes.back.death: true
      huskhomes.tpa: true
      huskhomes.tpahere: true
      huskhomes.spawn: true
      huskhomes.warp: true
  huskhomes.commands:
    description: Access all HuskHomes commands
    children:
      huskhomes.home: true
      huskhomes.sethome: true
      huskhomes.delhome: true
      huskhomes.edithome: true
      huskhomes.edithome.public: true
      huskhomes.publichome: true
      huskhomes.back: true
      huskhomes.back.death: true
      huskhomes.tp: true
      huskhomes.tphere: true
      huskhomes.tpa: true
      huskhomes.tpahere: true
      huskhomes.spawn: true
      huskhomes.spawn.set: true
      huskhomes.warp: true
      huskhomes.setwarp: true
      huskhomes.delwarp: true
      huskhomes.editwarp: true
      huskhomes.rtp: true
      huskhomes.about: true
      huskhomes.version_checker: true
      huskhomes.reload: true
  huskhomes.bypass_timer:
    description: Allows you to bypass the teleportation timer
    default: false
  huskhomes.home:
    description: Allows you to teleport to a home
    default: true
  huskhomes.home.other:
    description: Allows you to teleport to all player homes
    default: op
  huskhomes.sethome:
    description: Allows you to set homes
    default: true
  huskhomes.delhome:
    description: Allows you to delete a home
    default: true
  huskhomes.delhome.other:
    description: Allows you to delete any player home
    default: op
  huskhomes.delhome.all:
    description: Allows you to delete all your homes
    default: true
  huskhomes.warp:
    description: Allows you to teleport to a warp
    default: true
  huskhomes.warp.*:
    description: Lets you access all warps even if permission-restricted
    default: op
  huskhomes.setwarp:
    description: Allows you to set server warps
    default: op
  huskhomes.delwarp:
    description: Allows you to delete a server warp
    default: op
  huskhomes.delwarp.all:
    description: Allows you to delete all server warps
    default: op
  huskhomes.publichome:
    description: Allows you to teleport to public homes
    default: true
  huskhomes.edithome:
    description: Allows you to edit home settings
    default: true
  huskhomes.edithome.other:
    description: Allows you to edit home settings for any home
    default: op
  huskhomes.editwarp:
    description: Allows you to edit home information
    default: op
  huskhomes.back:
    description: Allows you to return to your last position
    default: true
  huskhomes.rtp:
    description: Allows you to randomly teleport
    default: true
  huskhomes.rtp.bypass_cooldown:
    description: Allows you to bypass the /rtp cooldown
    default: false
  huskhomes.about:
    description: View information about the plugin
    default: true
  huskhomes.reload:
    description: Reload the plugin configuration & messages files
    default: op
  huskhomes.version_checker:
    description: Check if the plugin is up-to-date
    default: op
  huskhomes.tp:
    description: Allows you to directly teleport to players or locations
    default: op
  huskhomes.tphere:
    description: Allows you to teleport players directly to your location
    default: op
  huskhomes.tprequest:
    description: Allows you to request to teleport to a player
    default: false
    children:
      - huskhomes.tpa
      - huskhomes.tpahere
      - huskhomes.tpaccept
      - huskhomes.tpdeny
  huskhomes.tpaccept:
    description: Allows you to accept teleport requests
    default: true
  huskhomes.tpdeny:
    description: Allows you to decline teleport requests
    default: true
  huskhomes.tpa:
    description: Allows you to request to teleport to a player
    default: true
  huskhomes.tpahere:
    description: Allows you to request a player to teleport to you
    default: true
  huskhomes.tpignore:
    description: Allows you to ingore teleport requests
    default: true
  huskhomes.tpoffline:
    description: Allows you to teleport to where players logged off
    default: op
  huskhomes.back.death:
    description: Allows you to return to where you died
    default: true
  huskhomes.spawn:
    description: Allows you to teleport to spawn
    default: true
  huskhomes.spawn.set:
    description: Allows you to set the spawn location
    default: op
  huskhomes.edithome.public:
    description: Allows you to make a home public
    default: true
  huskhomes.tpaall:
    description: Allows you to request everyone to teleport to you
    default: op
  huskhomes.tpall:
    description: Allows you to teleport everyone to you
    default: op